name: Test action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install Vulkan
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-13, macos-15, windows-2025, windows-11-arm ]
        vulkan: [ latest, 1.4.313.0 ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: ${{ matrix.vulkan }}
      - name: Verify SDK install
        run: |
          if [[ -x "$(command -v vkvia)" ]]; then
            vkvia --disable_cube_tests;
          fi

          echo "Vulkan SDK: $VULKAN_SDK"
          echo "PATH: $PATH"

          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"

          echo "VK_ICD_FILENAMES: $VK_ICD_FILENAMES"

          echo "VK_ADD_LAYER_PATH: $VK_ADD_LAYER_PATH"

          echo "VK_LAYER_PATH: $VK_LAYER_PATH"
        shell: bash
