name: Test action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install Vulkan
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-13, macos-15, windows-2025, windows-11-arm ]
        vulkan: [ latest, 1.4.313.0 ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: ${{ matrix.vulkan }}
      - name: Verify SDK install
        run: |
          if [[ -x "$(command -v vkvia)" ]]; then
            vkvia --disable_cube_tests;
          fi
        shell: bash
